// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDXiA3afOwaEaJsuHxlL_UcRrDPWu_MLE',
    appId: '1:366474321017:web:75775479b68326cb6208a8',
    messagingSenderId: '366474321017',
    projectId: 'yenyen-df2e8',
    authDomain: 'yenyen-df2e8.firebaseapp.com',
    storageBucket: 'yenyen-df2e8.firebasestorage.app',
    measurementId: 'G-YW42KEE42M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFR1skx_DaJrrZVXaSATekhYBVwWDS3w',
    appId: '1:366474321017:android:c25bb593d051db926208a8',
    messagingSenderId: '366474321017',
    projectId: 'yenyen-df2e8',
    storageBucket: 'yenyen-df2e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOPfQl8shlZRwe3PvHzPw776nEyI0eUWQ',
    appId: '1:366474321017:ios:8ad8df46d0bb6d1c6208a8',
    messagingSenderId: '366474321017',
    projectId: 'yenyen-df2e8',
    storageBucket: 'yenyen-df2e8.firebasestorage.app',
    iosBundleId: 'com.example.yenyen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOPfQl8shlZRwe3PvHzPw776nEyI0eUWQ',
    appId: '1:366474321017:ios:8ad8df46d0bb6d1c6208a8',
    messagingSenderId: '366474321017',
    projectId: 'yenyen-df2e8',
    storageBucket: 'yenyen-df2e8.firebasestorage.app',
    iosBundleId: 'com.example.yenyen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDXiA3afOwaEaJsuHxlL_UcRrDPWu_MLE',
    appId: '1:366474321017:web:b1b84bfb343c856e6208a8',
    messagingSenderId: '366474321017',
    projectId: 'yenyen-df2e8',
    authDomain: 'yenyen-df2e8.firebaseapp.com',
    storageBucket: 'yenyen-df2e8.firebasestorage.app',
    measurementId: 'G-75RVZY6FTR',
  );
}
